# Generated by Django 4.1.7 on 2023-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROCESS', 'В процессе'), ('DONE', 'Сделано')], default='NEW', max_length=30, verbose_name='Статус')),
                ('date_to_do', models.CharField(max_length=10, verbose_name='Дата выполнения')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
            ],
        ),
    ]
